### ISSUE TITLE
Not correctly sending user password.

### ISSUE THREAD

**Issue by jrsewing1** [bitfocus/companion-module-qsys-remote-control#1]
I was testing this on the Q-sys emulator and noticed that the login always sends the username in to password field. I was able to correct this by changing line 1751768 of the app.asar file. It originally had: 
`let login = '{ "jsonrpc":"2.0", "method":"Logon", "params": { "User":"' + self.config.user + '", "Password":"' + self.config.user + '" } }' + '\r';`
I changed to:
`let login = '{ "jsonrpc":"2.0", "method":"Logon", "params": { "User":"' + self.config.user + '", "Password":"' + self.config.pass + '" } }' + '\r';`
and was able to see the correct string being sent to the api over wireshark

Thank you for putting this together, I hope to use this for an upcoming project when i can get it all working.

**Comment by JeffreyDavidsz** [comment]
Good catch! This was actually fixed 4 months ago, so I would say update to 2.0. is you are using Atem wait a little longer, theres a bug in Atem at the moment
